# Site settings
title: Jonny Rigged Kitchen
email: jonotron@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a food blog. Pizza, sous vide, and whatever else I feel like
  cooking and documenting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kitchen.jonnyrigged.com" # the base hostname & protocol for your site
twitter_username: thejonotron

# Build settings
markdown: kramdown
